"""
LLM Response Cache with Deterministic Key Generation and Cost/Latency Metrics.
Supports exact matching, TTL expiration, and detailed savings telemetry.
"""

import hashlib
import json
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Union
from ttl_cache import TTLCache


@dataclass
class CacheMetrics:
    hits: int = 0
    misses: int = 0
    tokens_saved: int = 0
    latency_saved_seconds: float = 0.0
    cost_saved_usd: float = 0.0

    @property
    def total_requests(self) -> int:
        return self.hits + self.misses

    @property
    def hit_rate(self) -> float:
        if self.total_requests == 0:
            return 0.0
        return self.hits / self.total_requests

    def summary(self) -> Dict[str, Any]:
        return {
            "total_requests": self.total_requests,
            "hits": self.hits,
            "misses": self.misses,
            "hit_rate_pct": round(self.hit_rate * 100, 2),
            "tokens_saved": self.tokens_saved,
            "latency_saved_seconds": round(self.latency_saved_seconds, 3),
            "cost_saved_usd": round(self.cost_saved_usd, 6),
        }


class LLMCache:
    """
    Deterministic LLM Response Cache.
    Key is generated by computing SHA256 of canonical JSON of input parameters.
    """

    # Estimated pricing per 1K tokens for cost savings calculations (Blended Prompt+Completion)
    MODEL_RATES_PER_1K: Dict[str, float] = {
        "gpt-4o": 0.005,
        "gpt-4o-mini": 0.0003,
        "claude-3-5-sonnet": 0.006,
        "llama-3.1-70b": 0.0008,
        "llama-3.1-8b": 0.0001,
        "default": 0.002,
    }

    def __init__(self, default_ttl_seconds: float = 3600.0, max_size: int = 2000):
        self._cache = TTLCache(default_ttl_seconds=default_ttl_seconds, max_size=max_size)
        self.metrics = CacheMetrics()

    @staticmethod
    def generate_cache_key(
        prompt_or_messages: Union[str, List[Dict[str, str]]],
        model: str,
        temperature: float = 0.0,
        top_p: float = 1.0,
        extra_params: Optional[Dict[str, Any]] = None,
    ) -> str:
        """
        Produce a deterministic SHA-256 hash of normalized request parameters.
        Normalizes whitespace and sorts keys.
        """
        canonical_payload: Dict[str, Any] = {
            "model": model.strip().lower(),
            "temperature": round(temperature, 4),
            "top_p": round(top_p, 4),
        }

        if isinstance(prompt_or_messages, str):
            canonical_payload["prompt"] = prompt_or_messages.strip()
        else:
            # Canonicalize message dictionaries
            normalized_messages = []
            for msg in prompt_or_messages:
                normalized_messages.append({
                    "role": msg.get("role", "").strip().lower(),
                    "content": msg.get("content", "").strip(),
                })
            canonical_payload["messages"] = normalized_messages

        if extra_params:
            for k in sorted(extra_params.keys()):
                canonical_payload[k] = extra_params[k]

        serialized = json.dumps(canonical_payload, sort_keys=True, ensure_ascii=True)
        return hashlib.sha256(serialized.encode("utf-8")).hexdigest()

    def get(
        self,
        cache_key: str,
        simulated_tokens: int = 150,
        simulated_original_latency: float = 0.8,
        model: str = "default",
    ) -> Optional[Dict[str, Any]]:
        """
        Look up cached response. If hit, updates telemetry metrics.
        """
        result = self._cache.get(cache_key)
        if result is not None:
            self.metrics.hits += 1
            tokens = result.get("usage", {}).get("total_tokens", simulated_tokens)
            orig_latency = result.get("latency_seconds", simulated_original_latency)

            self.metrics.tokens_saved += tokens
            self.metrics.latency_saved_seconds += orig_latency

            rate = self.MODEL_RATES_PER_1K.get(model.lower(), self.MODEL_RATES_PER_1K["default"])
            self.metrics.cost_saved_usd += (tokens / 1000.0) * rate
            return result

        self.metrics.misses += 1
        return None

    def put(
        self,
        cache_key: str,
        response_data: Dict[str, Any],
        ttl_seconds: Optional[float] = None,
    ) -> None:
        """Store generated LLM response."""
        self._cache.set(cache_key, response_data, ttl_seconds=ttl_seconds)

    def invalidate(self, cache_key: str) -> bool:
        """Manually invalidate a cache entry."""
        return self._cache.delete(cache_key)

    def clear(self) -> None:
        """Clear cache and reset metrics."""
        self._cache.clear()
        self.metrics = CacheMetrics()

    def get_metrics(self) -> Dict[str, Any]:
        """Return metrics snapshot."""
        return self.metrics.summary()


if __name__ == "__main__":
    cache = LLMCache()
    key1 = cache.generate_cache_key("What is RAG?", model="gpt-4o-mini", temperature=0.0)
    key2 = cache.generate_cache_key("What is RAG?  ", model="GPT-4o-mini", temperature=0.0)
    assert key1 == key2, "Key normalization should produce identical hash"

    # Miss
    assert cache.get(key1) is None
    # Put
    cache.put(key1, {"text": "Retrieval Augmented Generation", "usage": {"total_tokens": 50}, "latency_seconds": 0.6})
    # Hit
    hit = cache.get(key1, model="gpt-4o-mini")
    assert hit is not None
    assert hit["text"] == "Retrieval Augmented Generation"
    metrics = cache.get_metrics()
    assert metrics["hits"] == 1
    assert metrics["misses"] == 1
    assert metrics["hit_rate_pct"] == 50.0
    print("LLMCache tests passed successfully!", metrics)
