"""
Schemas Module
Pydantic data models for structured inputs, outputs, tool invocations,
intermediate reasoning steps, memory checkpoints, and final research reports.
"""

from typing import List, Optional, Dict, Any, Literal
from pydantic import BaseModel, Field
import time


class ToolCall(BaseModel):
    """Represents a discrete tool invocation requested by the Agent Node."""
    tool_name: Literal["document_search", "calculator"] = Field(
        ..., description="The name of the tool to invoke."
    )
    tool_input: Dict[str, Any] = Field(
        ..., description="Key-value arguments required by the specified tool."
    )
    reasoning: Optional[str] = Field(
        None, description="The rationale for invoking this specific tool at this step."
    )


class ToolResult(BaseModel):
    """Represents the observation returned from a Tool Node execution."""
    tool_name: str
    tool_input: Dict[str, Any]
    output: Any
    success: bool = True
    error: Optional[str] = None


class Citation(BaseModel):
    """Represents a verifiable source reference retrieved during research."""
    source_id: str = Field(..., description="Unique identifier for the source")
    title: str = Field(..., description="Title of the paper or document")
    snippet: str = Field(..., description="Relevant text excerpt extracted from the source")
    score: float = Field(default=1.0, description="Relevance score")


class MemoryEntry(BaseModel):
    """Individual conversation or research insight preserved in session memory."""
    turn_id: int
    query: str
    summary: str
    key_facts: List[str] = Field(default_factory=list)
    timestamp: float = Field(default_factory=time.time)


class CheckpointRecord(BaseModel):
    """Snapshot metadata of a StateGraph execution checkpoint."""
    checkpoint_id: str
    thread_id: str
    step_index: int
    node_name: str
    timestamp: float = Field(default_factory=time.time)
    state_snapshot: Dict[str, Any]


class AgentThought(BaseModel):
    """Structured internal reasoning generated by the Agent Node."""
    thought: str = Field(..., description="Analysis of current query and accumulated evidence.")
    action_type: Literal["call_tool", "finish"] = Field(
        ..., description="Whether to call another tool or finalize the answer."
    )
    tool_call: Optional[ToolCall] = Field(
        None, description="Tool details if action_type is 'call_tool'."
    )
    draft_answer: Optional[str] = Field(
        None, description="Preliminary synthesized findings if action_type is 'finish'."
    )


class ResearchReport(BaseModel):
    """Final synthesized research report produced by the Answer Node."""
    query: str = Field(..., description="The original user research question.")
    session_id: str = Field(default="default_session", description="Associated session thread ID.")
    executive_summary: str = Field(..., description="High-level synthesis of findings.")
    detailed_analysis: str = Field(..., description="Detailed architectural and mathematical breakdown.")
    key_metrics: Dict[str, Any] = Field(
        default_factory=dict, description="Quantitative data, parameter counts, FLOPs, scaling metrics."
    )
    citations: List[Citation] = Field(
        default_factory=list, description="All grounded source citations used in the report."
    )
    graph_trajectory: List[str] = Field(
        default_factory=list, description="Step-by-step state graph execution trace."
    )
