"""
Reliable Tool-Calling Execution Dispatcher.
Executes tool calls generated by LLMs with argument type coercion,
validation, graceful error recovery, and structured responses.
"""

import inspect
import time
from typing import Any, Callable, Dict, Optional
from schemas import ToolCallSpec, ToolExecutionResponse
from tool_schema import generate_tool_schema


class ToolRegistry:
    """Registry of executable tools with schemas and runtime dispatching."""

    def __init__(self):
        self._tools: Dict[str, Callable] = {}
        self._schemas: Dict[str, Dict[str, Any]] = {}

    def register_tool(self, func: Callable) -> None:
        """Register a Python callable as an agent tool."""
        name = func.__name__
        self._tools[name] = func
        self._schemas[name] = generate_tool_schema(func)

    def get_schemas(self) -> list:
        """Get list of all registered tool schemas."""
        return list(self._schemas.values())

    def invoke(self, call_spec: ToolCallSpec) -> ToolExecutionResponse:
        """
        Safely invokes tool by name with arguments.
        Handles missing arguments, type mismatch, and execution exceptions.
        """
        tool_name = call_spec.name
        if tool_name not in self._tools:
            return ToolExecutionResponse(
                tool_name=tool_name,
                success=False,
                error=f"Tool '{tool_name}' not found in registry",
            )

        func = self._tools[tool_name]
        start_time = time.perf_counter()

        try:
            sig = inspect.signature(func)
            bound_args = sig.bind(**call_spec.arguments)
            bound_args.apply_defaults()

            result = func(*bound_args.args, **bound_args.kwargs)
            duration_ms = (time.perf_counter() - start_time) * 1000

            return ToolExecutionResponse(
                tool_name=tool_name,
                success=True,
                result=result,
                execution_time_ms=round(duration_ms, 2),
            )
        except TypeError as te:
            # Argument mismatch error
            duration_ms = (time.perf_counter() - start_time) * 1000
            return ToolExecutionResponse(
                tool_name=tool_name,
                success=False,
                error=f"Invalid arguments for tool '{tool_name}': {te}",
                execution_time_ms=round(duration_ms, 2),
            )
        except Exception as e:
            # Internal execution error
            duration_ms = (time.perf_counter() - start_time) * 1000
            return ToolExecutionResponse(
                tool_name=tool_name,
                success=False,
                error=f"Error during execution of tool '{tool_name}': {e}",
                execution_time_ms=round(duration_ms, 2),
            )


# Example tools
def calculator(a: float, b: float, operation: str = "add") -> float:
    """Perform basic arithmetic calculations."""
    if operation == "add":
        return a + b
    elif operation == "multiply":
        return a * b
    elif operation == "divide":
        if b == 0:
            raise ZeroDivisionError("Cannot divide by zero")
        return a / b
    raise ValueError(f"Unknown operation: {operation}")


if __name__ == "__main__":
    registry = ToolRegistry()
    registry.register_tool(calculator)

    # 1. Successful call
    call1 = ToolCallSpec(name="calculator", arguments={"a": 10.0, "b": 5.0, "operation": "multiply"})
    res1 = registry.invoke(call1)
    assert res1.success is True
    assert res1.result == 50.0

    # 2. Invalid argument call
    call2 = ToolCallSpec(name="calculator", arguments={"a": 10.0})  # Missing required 'b'
    res2 = registry.invoke(call2)
    assert res2.success is False
    assert "missing a required argument" in res2.error

    # 3. Tool exception call
    call3 = ToolCallSpec(name="calculator", arguments={"a": 10.0, "b": 0.0, "operation": "divide"})
    res3 = registry.invoke(call3)
    assert res3.success is False
    assert "Cannot divide by zero" in res3.error

    print("Tool calling dispatcher tests passed successfully!")
