"""
State Module for StateGraph Research Agent
Defines the unified Graph State data structure passed between Nodes.
State is immutable across node transitions and updated via functional state reducers.
"""

from typing import TypedDict, List, Dict, Any, Optional
from schemas import ToolCall, ToolResult, Citation, AgentThought, ResearchReport


class ResearchState(TypedDict, total=False):
    """
    Central State passed between nodes in the State Graph.
    
    Fields:
        query (str): The research question submitted by the user.
        messages (List[Dict[str, str]]): Conversational memory of thoughts, queries, and observations.
        step_count (int): Current iteration index in the graph loop.
        max_steps (int): Safety threshold to prevent infinite cyclic transitions.
        plan (List[str]): Decomposed sub-goals or research milestones.
        current_thought (Optional[AgentThought]): The latest reasoning step produced by Agent Node.
        pending_tool_calls (List[ToolCall]): Tools scheduled for execution by Tool Node.
        tool_history (List[ToolResult]): Full execution log of all invoked tools with outputs.
        observations (List[str]): Contextual excerpts accumulated from tools.
        citations (List[Citation]): Unique verified citations collected across search passes.
        calculation_cache (Dict[str, Any]): Evaluated mathematical expressions.
        draft_answer (Optional[str]): Preliminary draft synthesized by Agent Node.
        final_report (Optional[ResearchReport]): Structured report generated by Answer Node.
        next_node (str): Routing directive determining the next graph transition.
        is_complete (bool): Terminal flag indicating research is finished.
        logs (List[str]): Detailed execution trace for debugging and visualization.
    """
    query: str
    messages: List[Dict[str, str]]
    step_count: int
    max_steps: int
    plan: List[str]
    current_thought: Optional[AgentThought]
    pending_tool_calls: List[ToolCall]
    tool_history: List[ToolResult]
    observations: List[str]
    citations: List[Citation]
    calculation_cache: Dict[str, Any]
    draft_answer: Optional[str]
    final_report: Optional[ResearchReport]
    next_node: str
    is_complete: bool
    logs: List[str]


def create_initial_state(query: str, max_steps: int = 8) -> ResearchState:
    """Instantiates a clean, initialized ResearchState for graph execution."""
    return {
        "query": query,
        "messages": [{"role": "user", "content": query}],
        "step_count": 0,
        "max_steps": max_steps,
        "plan": [],
        "current_thought": None,
        "pending_tool_calls": [],
        "tool_history": [],
        "observations": [],
        "citations": [],
        "calculation_cache": {},
        "draft_answer": None,
        "final_report": None,
        "next_node": "agent",
        "is_complete": False,
        "logs": [f"[INIT] StateGraph initialized with query: '{query}'"],
    }
